"""
init core models
"""

from yoyo import step

__depends__ = {'20210327_01_VbzNE-add-constrain-to-user'}

steps = [
    step("""CREATE TABLE boards (
                            uuid UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                            name VARCHAR(47), 
                            description VARCHAR(1024),
                            users_uid UUID REFERENCES users(uid) ON DELETE CASCADE
                )"""),
    step("""CREATE TABLE method_statuses (
                            id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
                            name VARCHAR(47) NULL, 
                            description VARCHAR(256) NULL 
                )""")
]
